### ISSUE TITLE
汉译南传大藏经中，有 cb:div 之外的段落出现

### ISSUE THREAD

**Issue by meng89** [cbeta-git/xml-p5a#12]
在 `/N/N18/N18n0006.xml` 中，有两个p元素游离于所属的 cb:div 之外：

```
<p xml:id="pN18p0158a1101" style="margin-left:22em">靜慮相應之初清淨經（終）</p>
<p xml:id="pN18p0158a1201" style="margin-left:2em;text-indent:2em">如念處（相應）可廣說。</p>
```

这两个元素内容上属于含有`<cb:mulu type="其他" level="4">〔一〕第一　初清淨</cb:mulu>` 的 cb:div 元素

**Comment by mahawu** [comment]
已將 0158a10 的 </cb:div> 移至 0158a13。謝謝！

maha

Chen Meng ***@***.***> 於 2024年6月21日 週五 下午9:34寫道：
