### ISSUE TITLE
N/N17/N17n0006.xml第4080行，似乎存在多余的 cb:div

### ISSUE THREAD

**Issue by meng89** [cbeta-git/xml-p5a#2]
在N/N17/N17n0006.xml中第4080行，以下部分的 cb:div 似乎多余，整个相应部里只有这个 tag 的第一个子元素不是 cb:mulu。
` 〇　序</cb:mulu><cb:div type="other"><head>一　舍衛城因緣。</head>`

**Comment by cbeta-git** [comment]
現在才注意到這裡有問題。查了一下，不只是標記問題，似乎原書排版就有錯誤，這要再進一步檢查。

**Comment by mahawu** [comment]
這請 heaven 看看。

maha

CBETA ***@***.***> 於 2022年10月17日 週一 清晨6:43寫道：

**Comment by cbeta-git** [comment]
已依建議修改，不更動經文位置。
