### ISSUE TITLE
相应部目录序号格式不统一

### ISSUE THREAD

**Issue by meng89** [cbeta-git/xml-p5a#3]
我是这样理解的，相应部的目录标题里，有两种序号，一种是第字开头的序号，如**第一**，另一种是带有六角括号的序号，如**〔一〕**。前一种的用意是指出此条目在当前级别里的序号，后一种是经文在当前相应篇章里的序号。

如果以上理解正确，那么下面这两个目录的序号就是正确：

> 第一　諸天相應
>　第一　葦品
> 　　〔一〕瀑流

> 第五　比丘尼相應
>　〔一〕第一　阿羅毘迦

但是下面的标题就不正确了：

> 第五　迦葉相應
>　第一　滿足

我大概浏览了一下，不正确序号在这些相应里都存在：迦葉相應、入相應、生相應、煩惱相應、舍利弗相应、禪定相應、閻浮車相應、沙門出家相應、目犍連相應、質多相應、聚落主相應、無記說相應。

而且 婆蹉種相應 中的序号是两种颠倒的，我浏览了其它版本的相应部，此相应应有55经，但是按照此目录里方括号的意思就只有11经。

如果 cbeta 愿意的话，我会修正后发一个 pull requests。
如果需要其它方式快速沟通的话请电邮我开发者群组的联系方式：observerchan@gmail.com

**Comment by heavenchou** [comment]
謝謝 meng89 提出這個現象，我查了一下原書，原書即是如此。

以底下的例子來說明。

第二　天子相應
.......
　第二　給孤獨品
　　〔一一〕第一　月自在

「月自在」是給狐獨品的第一經，但因為它是天子相應的第 11 經，所以特別標上〔一一〕，這樣才方便計算該經在該相應的位置。

而您提到那些沒有標明的經號，因為它們都只有一品，所以不用另外再標一個經號來表示在該相應的位置。

至於婆蹉種相應，原書也是如此處理，它大概是把中括號當成是某種分類的處理法，不同於其它是相應的經號數。

真正的小經號依然有 55 經，這點是沒有問題的。

**Comment by meng89** [comment]
可是 比丘尼相應、婆耆沙長老相應、夜叉相應 等相应，也仅有一品，但是仍然有方括号标注的序号。这就是我想说的序号格式不一致的地方。因为经常有人用 **SN 1.1** 这样的方式指代某相应中的某经。如果修复成一致的话，会更加易于别人查找：找到某相应，然后再寻找方括号里的序号就能找到想找的经文了。
我想知道cbeta是否愿意把相应部目录修改成一致。

**Comment by heavenchou** [comment]
的確是如此，看來有些單品就沒有使用方括號的經號了。
不過依現有的狀況，依舊很容易判斷經號，有方括就依方括，沒方括就是原來的經號，由目錄也很容易看出來。

我們會再討論看看，再決定是尊重原書的安排，或是統一加方括號，或是統一單品不加方括號。

**Comment by heavenchou** [comment]
的確是如此，看來有些單品依然使用方括號的經號。
不過依現有的狀況，依舊很容易判斷經號，有方括就依方括，沒方括就是原來的經號，由目錄也很容易看出來。

我們會再討論看看，再決定是尊重原書的安排，或是統一加方括號，或是統一單品不加方括號。

**Comment by meng89** [comment]
@heavenchou 不知道现在有没有讨论出最终决定。

**Comment by mahawu** [comment]
我這邊已經改好 xml-p5a 了，CBETA 下一季(十月) 會更新。

maha

Chen Meng ***@***.***> 於 2022年9月27日 週二 上午9:22寫道：

**Comment by meng89** [comment]
@mahawu 可以预告一下是哪种方案吗？

**Comment by mahawu** [comment]
主要是修改 mulu 標記，大致上是依照你提出的方案來執行了。你可以下載來看看。

maha

Chen Meng ***@***.***> 於 2022年9月27日 週二 上午10:49寫道：

**Comment by meng89** [comment]
原来7天前就修改了，是我不细心。感谢CBETA！

**Comment by mahawu** [comment]
很感謝你提出這個議題。日後請多指教。

maha

Chen Meng ***@***.***> 於 2022年9月27日 週二 下午1:53寫道：

**Comment by meng89** [comment]
按照修改后的规则解析了一下，发现在 N/N15/N15n0006.xml 中只有一处格式有点不同：
`<cb:mulu type="其他" level="3">第〔六〕六　想</cb:mulu>`

可能应是这样：
<cb:mulu type="其他" level="3">〔六〕第六　想</cb:mulu>

**Comment by cbeta-git** [comment]
我正在做本季更新處理，隨後我就會修改。

     heaven

Chen Meng 於 2022/10/15 下午 11:28 寫道:

**Comment by mahawu** [comment]
謝謝 heaven！

maha

CBETA ***@***.***> 於 2022年10月15日 週六 晚上11:46寫道：
