### ISSUE TITLE
app中兩個嵌套的cf note

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-git/xml-p5a#5]
文件：`T/T04/T04n0210.xml`
```xml
	<note type="cf5">Udānavarga 31.45 (Bernhard, Franz (ed) 1965, Udānavarga, Band I, Sanskrittexteaus der Turfanfunden X, Vandenhoeck &amp; Ruprecht, Göttingen.)
		<note type="cf6">Patna Dharmapada 88 (Cone, Margarent 1989, Journal of the Pali Text Society, Volume XIII, p. 126.)</note>
	</note>
```
其中 cf5 和 cf6 似乎應該是並列關係。

### 附：
另外，這個地方前面還有 cf1 cf2 cf3，但是存在於app.lem裏的。這兩處是否也應在lem中？

雖然我看到 5、6與1、2、3的區別很明顯，一個是行號，一個是說明文字。但似乎在cbetaonline中只會展示lem中的note，5、6這種沒有展示出來。也許展示出來也是很有價值的參考。

類似的，note出現在lem和rdg之間,，從而在cbetaonline上沒有展示出來的情況，還出現在以下文件：
文件：`T/T02/T02n0099.xml`
```xml
<app from="#beg0336a1301" to="#end0336a1301"><lem wit="#wit.cbeta" resp="#resp1">己</lem><rdg wit="#wit.orig">已</rdg><rdg wit="#wit1">巳</rdg><note type="cf1">QC057_p058610</note></app>
```
文件：`ZS/ZS01/ZS01n0001.xml`
```xml
<app from="#beg0312a1001" to="#end0312a1001"><lem wit="#wit.cbeta" resp="#resp4">金</lem><note type="cf1">根據原書所附勘誤表</note><rdg wit="#wit.orig">全</rdg></app>
```

**Comment by mahawu** [comment]
謝謝！已修訂好了。

maha

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
乾淨無病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

没——问题 ***@***.***> 於 2023年7月3日 週一 下午1:11寫道：
