### ISSUE TITLE
cb:jhead 有的時候不是卷標題

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-git/xml-p5a#6]
一直以爲 `jhead` 是卷專用的。剛發現很多“品”題也是用jhead標籤。如：
```
T/T15/T15n0649.xml:<lb n="0736a16" ed="T"/><cb:jhead type="pin"><anchor xml:id="nkr_note_orig_0736002" n="0736002"/><anchor xml:id="nkr_note_mod_0736002" n="0736002"/><anchor xml:id="beg0736002" n="0736002"/>先世勤相應品第二之二<anchor xml36002"/></cb:jhead></cb:juan>
```

`grep 'jhead type' -r xml-p5a` 能看到很多。

但是也有很多 `type="pin"`是用的 `head`標籤。如：
```
T/T12/T12n0375.xml:<lb n="0761c24" ed="T"/><cb:div type="pin"><head type="pin"><anchor xml:id="fxT12p0761c07"/>光明遍照高貴德王菩薩品<anchor xml:id="nkr_note_orig_0761018" n="0761018"/><anchor xml:id="nkr_note_mod_0761018" n="0761018"/><anchor xml:id="beg0761018" n="0761018"/>之<anchor xml:id="end0761018"/>六</head>
``` 

`grep '<head type' -r xml-p5a`可以看到很多。

所以這個應該是處於混用的狀態，目前沒法通過標籤名來判斷是否是卷標題了。。。煩請評估是否有必要統一。

**Comment by heavenchou** [comment]
您好，參考說明如下：

1. &lt;juan> 是「卷首資訊」或「卷尾資訊」，&lt;juan> 裡面的 &lt;jhead> 是「juan head」（卷首資訊 或 卷尾資訊 裡的標題）

2. 內容標記的確會有認定不同的問題，以 T15n0649_p0736a16 為例，這裡確實是「卷首資訊」：

    T15n0649_p0736a13：觀察諸法行經卷第三
    T15n0649_p0736a14：
    T15n0649_p0736a15：隋[＊]天竺三[＊]藏闍那崛多譯
    T15n0649_p0736a16：[2]先世勤相應品第二之二


或許也可以判讀 736a16 的品名「不是」卷首資訊，  
但如果觀察 T15n0649 的第二卷、第三卷，可以看到「先世勤相應品」是重複出現的，  
因此 736a16 不能標為 div/head.  
因為分卷，所以這個品名在卷首重複出現，將之判讀為「卷首資訊」裡的「標題」，我認為是合理的。

3. 或許也可以說，736a13「觀察諸法行經卷第三」才是「卷標題」，736a16 的品名不是，  
這樣的邏輯，我覺得也合理，  
736a16「先世勤相應品第二之二」仍然視為「卷首資訊」的一部分，但不標 jhead，或許標 p?
不過 CBETA 已累積了許多文本，不太可能回頭一一檢視、修訂。
只能等有大整頓的時間時，再來好好整修一番。

4. 如果想要知道佛典在什麼地方分卷，建議使用 &lt;milestone unit="juan">

5. 如果希望如上述第3點，「觀察諸法行經卷第三」才是「卷標題」，736a16 的品名不是，  
目前可以判斷是否為 juan 下的第一個 jhead.

6. &lt;head type="pin"> 一般出現在 div 下，這是 章節標題，當 章節標題 為 品名 時，會加上 type="pin" 屬性。

7. 使用 CBETA XML，建議使用 XML Parser，根據元素所在的上下文，判斷標記意義。
例如 &lt;head> 可能出現在 div 下，也可能出現在 lg, list 下面。

**Comment by RayCHOU** [comment]
@heavenchou 
提到 xml 標記的地方好像都失去了，是因為從 email 回復的原因？

> 1. 是「卷首資訊」或「卷尾資訊」， 裡面的  是「juan head」（卷首資訊 或 卷尾資訊 裡的標題）
> 4. 如果想要知道佛典在什麼地方分卷，建議使用

**Comment by heavenchou** [comment]
> @heavenchou 提到 xml 標記的地方好像都失去了，是因為從 email 回復的原因？

我是在 github 直接貼的，沒注意到標記不見了，剛已補上了。
從 email 回覆的好像一直沒有出現在這裡。
