### ISSUE TITLE
標點被放在<p>標籤之外了

### ISSUE THREAD

**Issue by CallMeNP** [cbeta-git/xml-p5a#8]
`T/T15/T15n0639/005.xml`
``` xml
<lb n="0577b25" ed="T"/>「<anchor type="circle"/><p xml:id="pT15p0577b2501">
```

現象就是標點單獨一段，內容另起一段。

**Comment by mahawu** [comment]
謝謝提報問題！剛修訂了，另有四筆類似情況也一併處理了。

CBETA bm 跟 xml-p5a 同步改了、上傳了。

maha

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
乾淨無病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

没——问题 ***@***.***> 於 2023年8月8日 週二 下午7:09寫道：
